//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace OSZN.ru.nalog.fias {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DownloadServiceSoap", Namespace="http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")]
    public partial class DownloadService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLastDownloadFileInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDownloadFileInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DownloadService() {
            this.Url = global::OSZN.Properties.Settings.Default.OSZN_ru_nalog_fias_DownloadService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLastDownloadFileInfoCompletedEventHandler GetLastDownloadFileInfoCompleted;
        
        /// <remarks/>
        public event GetAllDownloadFileInfoCompletedEventHandler GetAllDownloadFileInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetLastDownloadFileI" +
            "nfo", RequestNamespace="http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", ResponseNamespace="http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DownloadFileInfo GetLastDownloadFileInfo() {
            object[] results = this.Invoke("GetLastDownloadFileInfo", new object[0]);
            return ((DownloadFileInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastDownloadFileInfoAsync() {
            this.GetLastDownloadFileInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetLastDownloadFileInfoAsync(object userState) {
            if ((this.GetLastDownloadFileInfoOperationCompleted == null)) {
                this.GetLastDownloadFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastDownloadFileInfoOperationCompleted);
            }
            this.InvokeAsync("GetLastDownloadFileInfo", new object[0], this.GetLastDownloadFileInfoOperationCompleted, userState);
        }
        
        private void OnGetLastDownloadFileInfoOperationCompleted(object arg) {
            if ((this.GetLastDownloadFileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastDownloadFileInfoCompleted(this, new GetLastDownloadFileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fias.nalog.ru/WebServices/Public/DownloadService.asmx/GetAllDownloadFileIn" +
            "fo", RequestNamespace="http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", ResponseNamespace="http://fias.nalog.ru/WebServices/Public/DownloadService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DownloadFileInfo[] GetAllDownloadFileInfo() {
            object[] results = this.Invoke("GetAllDownloadFileInfo", new object[0]);
            return ((DownloadFileInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDownloadFileInfoAsync() {
            this.GetAllDownloadFileInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDownloadFileInfoAsync(object userState) {
            if ((this.GetAllDownloadFileInfoOperationCompleted == null)) {
                this.GetAllDownloadFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDownloadFileInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllDownloadFileInfo", new object[0], this.GetAllDownloadFileInfoOperationCompleted, userState);
        }
        
        private void OnGetAllDownloadFileInfoOperationCompleted(object arg) {
            if ((this.GetAllDownloadFileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDownloadFileInfoCompleted(this, new GetAllDownloadFileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fias.nalog.ru/WebServices/Public/DownloadService.asmx")]
    public partial class DownloadFileInfo {
        
        private int versionIdField;
        
        private string textVersionField;
        
        private string fiasCompleteDbfUrlField;
        
        private string fiasCompleteXmlUrlField;
        
        private string fiasDeltaDbfUrlField;
        
        private string fiasDeltaXmlUrlField;
        
        private string kladr4ArjUrlField;
        
        private string kladr47ZUrlField;
        
        /// <remarks/>
        public int VersionId {
            get {
                return this.versionIdField;
            }
            set {
                this.versionIdField = value;
            }
        }
        
        /// <remarks/>
        public string TextVersion {
            get {
                return this.textVersionField;
            }
            set {
                this.textVersionField = value;
            }
        }
        
        /// <remarks/>
        public string FiasCompleteDbfUrl {
            get {
                return this.fiasCompleteDbfUrlField;
            }
            set {
                this.fiasCompleteDbfUrlField = value;
            }
        }
        
        /// <remarks/>
        public string FiasCompleteXmlUrl {
            get {
                return this.fiasCompleteXmlUrlField;
            }
            set {
                this.fiasCompleteXmlUrlField = value;
            }
        }
        
        /// <remarks/>
        public string FiasDeltaDbfUrl {
            get {
                return this.fiasDeltaDbfUrlField;
            }
            set {
                this.fiasDeltaDbfUrlField = value;
            }
        }
        
        /// <remarks/>
        public string FiasDeltaXmlUrl {
            get {
                return this.fiasDeltaXmlUrlField;
            }
            set {
                this.fiasDeltaXmlUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Kladr4ArjUrl {
            get {
                return this.kladr4ArjUrlField;
            }
            set {
                this.kladr4ArjUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Kladr47ZUrl {
            get {
                return this.kladr47ZUrlField;
            }
            set {
                this.kladr47ZUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetLastDownloadFileInfoCompletedEventHandler(object sender, GetLastDownloadFileInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastDownloadFileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastDownloadFileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DownloadFileInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DownloadFileInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllDownloadFileInfoCompletedEventHandler(object sender, GetAllDownloadFileInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDownloadFileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDownloadFileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DownloadFileInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DownloadFileInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591